"""initial

Revision ID: d708ee386954
Revises: 
Create Date: 2026-03-04 12:08:57.738720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd708ee386954'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scan_status_enum', native_enum=False), nullable=False),
    sa.Column('phase', sa.Enum('RECON', 'DISCOVERY', 'FINGERPRINT', 'EXPLOITATION', name='scan_phase_enum', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('os_family', sa.String(length=128), nullable=True),
    sa.Column('os_distribution', sa.String(length=255), nullable=True),
    sa.Column('os_kernel', sa.String(length=128), nullable=True),
    sa.Column('uptime', sa.String(length=64), nullable=True),
    sa.Column('hops', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UP', 'DOWN', 'FILTERED', name='host_status_enum', native_enum=False), nullable=False),
    sa.Column('node_type', sa.Enum('GATEWAY', 'SERVER', 'WORKSTATION', 'PRINTER', 'UNKNOWN', name='node_type_enum', native_enum=False), nullable=False),
    sa.Column('open_ports', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_discovered_at'), 'hosts', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_hosts_ip_address'), 'hosts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_hosts_scan_id'), 'hosts', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hosts_scan_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_ip_address'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_discovered_at'), table_name='hosts')
    op.drop_table('hosts')
    op.drop_table('scans')
    # ### end Alembic commands ###
